'use strict';

module.exports = {
  up: async (queryInterface, Sequelize) => {
    return queryInterface.bulkInsert('doctors', [
      {
        picture: "/images/Member01S0101.png",
        alttext: "樊志偉醫生",
        slug: "樊志偉醫生",
        en_metaname: "泌尿外科專科醫生",
        tc_metaname: "泌尿外科專科醫生",
        sc_metaname: "泌尿外科專科醫生",
        en_metadesc: "周醫生是家庭醫學專科醫生，他在慢性疾病管理（例如高血壓，糖尿病和心理健康）方面經驗豐富。",
        tc_metadesc: "周醫生是家庭醫學專科醫生，他在慢性疾病管理（例如高血壓，糖尿病和心理健康）方面經驗豐富。",
        sc_metadesc: "周醫生是家庭醫學專科醫生，他在慢性疾病管理（例如高血壓，糖尿病和心理健康）方面經驗豐富。",
        en_name: "Dr. Fan Zhiwei",
        tc_name: "樊志偉醫生",
        sc_name: "樊志伟医生",
        en_title: "泌尿外科專科醫生",
        tc_title: "泌尿外科專科醫生",
        sc_title: "泌尿外科專科醫生",
        en_description: "周醫生是家庭醫學專科醫生，他在慢性疾病管理（例如高血壓，糖尿病和心理健康）方面經驗豐富。",
        tc_description: "周醫生是家庭醫學專科醫生，他在慢性疾病管理（例如高血壓，糖尿病和心理健康）方面經驗豐富。",
        sc_description: "周醫生是家庭醫學專科醫生，他在慢性疾病管理（例如高血壓，糖尿病和心理健康）方面經驗豐富。",
        en_dialect: "英語，粵語及普通話",
        tc_dialect: "英語，粵語及普通話",
        sc_dialect: "英語，粵語及普通話",
        en_clinic: "門診：銅鑼灣診所",
        tc_clinic: "門診：銅鑼灣診所",
        sc_clinic: "門診：銅鑼灣診所",
        visible: true,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        picture: "/images/Member01S0101.png",
        alttext: "樊志偉醫生",
        slug: "樊志偉醫生",
        en_metaname: "泌尿外科專科醫生",
        tc_metaname: "泌尿外科專科醫生",
        sc_metaname: "泌尿外科專科醫生",
        en_metadesc: "周醫生是家庭醫學專科醫生，他在慢性疾病管理（例如高血壓，糖尿病和心理健康）方面經驗豐富。",
        tc_metadesc: "周醫生是家庭醫學專科醫生，他在慢性疾病管理（例如高血壓，糖尿病和心理健康）方面經驗豐富。",
        sc_metadesc: "周醫生是家庭醫學專科醫生，他在慢性疾病管理（例如高血壓，糖尿病和心理健康）方面經驗豐富。",
        en_name: "Dr. Fan Zhiwei",
        tc_name: "樊志偉醫生",
        sc_name: "樊志伟医生",
        en_title: "泌尿外科專科醫生",
        tc_title: "泌尿外科專科醫生",
        sc_title: "泌尿外科專科醫生",
        en_description: "周醫生是家庭醫學專科醫生，他在慢性疾病管理（例如高血壓，糖尿病和心理健康）方面經驗豐富。",
        tc_description: "周醫生是家庭醫學專科醫生，他在慢性疾病管理（例如高血壓，糖尿病和心理健康）方面經驗豐富。",
        sc_description: "周醫生是家庭醫學專科醫生，他在慢性疾病管理（例如高血壓，糖尿病和心理健康）方面經驗豐富。",
        en_dialect: "英語，粵語及普通話",
        tc_dialect: "英語，粵語及普通話",
        sc_dialect: "英語，粵語及普通話",
        en_clinic: "門診：銅鑼灣診所",
        tc_clinic: "門診：銅鑼灣診所",
        sc_clinic: "門診：銅鑼灣診所",
        visible: true,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        picture: "/images/Member01S0101.png",
        alttext: "樊志偉醫生",
        slug: "樊志偉醫生",
        en_metaname: "泌尿外科專科醫生",
        tc_metaname: "泌尿外科專科醫生",
        sc_metaname: "泌尿外科專科醫生",
        en_metadesc: "周醫生是家庭醫學專科醫生，他在慢性疾病管理（例如高血壓，糖尿病和心理健康）方面經驗豐富。",
        tc_metadesc: "周醫生是家庭醫學專科醫生，他在慢性疾病管理（例如高血壓，糖尿病和心理健康）方面經驗豐富。",
        sc_metadesc: "周醫生是家庭醫學專科醫生，他在慢性疾病管理（例如高血壓，糖尿病和心理健康）方面經驗豐富。",
        en_name: "Dr. Fan Zhiwei",
        tc_name: "樊志偉醫生",
        sc_name: "樊志伟医生",
        en_title: "泌尿外科專科醫生",
        tc_title: "泌尿外科專科醫生",
        sc_title: "泌尿外科專科醫生",
        en_description: "周醫生是家庭醫學專科醫生，他在慢性疾病管理（例如高血壓，糖尿病和心理健康）方面經驗豐富。",
        tc_description: "周醫生是家庭醫學專科醫生，他在慢性疾病管理（例如高血壓，糖尿病和心理健康）方面經驗豐富。",
        sc_description: "周醫生是家庭醫學專科醫生，他在慢性疾病管理（例如高血壓，糖尿病和心理健康）方面經驗豐富。",
        en_dialect: "英語，粵語及普通話",
        tc_dialect: "英語，粵語及普通話",
        sc_dialect: "英語，粵語及普通話",
        en_clinic: "門診：銅鑼灣診所",
        tc_clinic: "門診：銅鑼灣診所",
        sc_clinic: "門診：銅鑼灣診所",
        visible: true,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        picture: "/images/Member01S0101.png",
        alttext: "樊志偉醫生",
        slug: "樊志偉醫生",
        en_metaname: "泌尿外科專科醫生",
        tc_metaname: "泌尿外科專科醫生",
        sc_metaname: "泌尿外科專科醫生",
        en_metadesc: "周醫生是家庭醫學專科醫生，他在慢性疾病管理（例如高血壓，糖尿病和心理健康）方面經驗豐富。",
        tc_metadesc: "周醫生是家庭醫學專科醫生，他在慢性疾病管理（例如高血壓，糖尿病和心理健康）方面經驗豐富。",
        sc_metadesc: "周醫生是家庭醫學專科醫生，他在慢性疾病管理（例如高血壓，糖尿病和心理健康）方面經驗豐富。",
        en_name: "Dr. Fan Zhiwei",
        tc_name: "樊志偉醫生",
        sc_name: "樊志伟医生",
        en_title: "泌尿外科專科醫生",
        tc_title: "泌尿外科專科醫生",
        sc_title: "泌尿外科專科醫生",
        en_description: "周醫生是家庭醫學專科醫生，他在慢性疾病管理（例如高血壓，糖尿病和心理健康）方面經驗豐富。",
        tc_description: "周醫生是家庭醫學專科醫生，他在慢性疾病管理（例如高血壓，糖尿病和心理健康）方面經驗豐富。",
        sc_description: "周醫生是家庭醫學專科醫生，他在慢性疾病管理（例如高血壓，糖尿病和心理健康）方面經驗豐富。",
        en_dialect: "英語，粵語及普通話",
        tc_dialect: "英語，粵語及普通話",
        sc_dialect: "英語，粵語及普通話",
        en_clinic: "門診：銅鑼灣診所",
        tc_clinic: "門診：銅鑼灣診所",
        sc_clinic: "門診：銅鑼灣診所",
        visible: true,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        picture: "/images/Member01S0101.png",
        alttext: "樊志偉醫生",
        slug: "樊志偉醫生",
        en_metaname: "泌尿外科專科醫生",
        tc_metaname: "泌尿外科專科醫生",
        sc_metaname: "泌尿外科專科醫生",
        en_metadesc: "周醫生是家庭醫學專科醫生，他在慢性疾病管理（例如高血壓，糖尿病和心理健康）方面經驗豐富。",
        tc_metadesc: "周醫生是家庭醫學專科醫生，他在慢性疾病管理（例如高血壓，糖尿病和心理健康）方面經驗豐富。",
        sc_metadesc: "周醫生是家庭醫學專科醫生，他在慢性疾病管理（例如高血壓，糖尿病和心理健康）方面經驗豐富。",
        en_name: "Dr. Fan Zhiwei",
        tc_name: "樊志偉醫生",
        sc_name: "樊志伟医生",
        en_title: "泌尿外科專科醫生",
        tc_title: "泌尿外科專科醫生",
        sc_title: "泌尿外科專科醫生",
        en_description: "周醫生是家庭醫學專科醫生，他在慢性疾病管理（例如高血壓，糖尿病和心理健康）方面經驗豐富。",
        tc_description: "周醫生是家庭醫學專科醫生，他在慢性疾病管理（例如高血壓，糖尿病和心理健康）方面經驗豐富。",
        sc_description: "周醫生是家庭醫學專科醫生，他在慢性疾病管理（例如高血壓，糖尿病和心理健康）方面經驗豐富。",
        en_dialect: "英語，粵語及普通話",
        tc_dialect: "英語，粵語及普通話",
        sc_dialect: "英語，粵語及普通話",
        en_clinic: "門診：銅鑼灣診所",
        tc_clinic: "門診：銅鑼灣診所",
        sc_clinic: "門診：銅鑼灣診所",
        visible: true,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        picture: "/images/Member01S0101.png",
        alttext: "樊志偉醫生",
        slug: "樊志偉醫生",
        en_metaname: "泌尿外科專科醫生",
        tc_metaname: "泌尿外科專科醫生",
        sc_metaname: "泌尿外科專科醫生",
        en_metadesc: "周醫生是家庭醫學專科醫生，他在慢性疾病管理（例如高血壓，糖尿病和心理健康）方面經驗豐富。",
        tc_metadesc: "周醫生是家庭醫學專科醫生，他在慢性疾病管理（例如高血壓，糖尿病和心理健康）方面經驗豐富。",
        sc_metadesc: "周醫生是家庭醫學專科醫生，他在慢性疾病管理（例如高血壓，糖尿病和心理健康）方面經驗豐富。",
        en_name: "Dr. Fan Zhiwei",
        tc_name: "樊志偉醫生",
        sc_name: "樊志伟医生",
        en_title: "泌尿外科專科醫生",
        tc_title: "泌尿外科專科醫生",
        sc_title: "泌尿外科專科醫生",
        en_description: "周醫生是家庭醫學專科醫生，他在慢性疾病管理（例如高血壓，糖尿病和心理健康）方面經驗豐富。",
        tc_description: "周醫生是家庭醫學專科醫生，他在慢性疾病管理（例如高血壓，糖尿病和心理健康）方面經驗豐富。",
        sc_description: "周醫生是家庭醫學專科醫生，他在慢性疾病管理（例如高血壓，糖尿病和心理健康）方面經驗豐富。",
        en_dialect: "英語，粵語及普通話",
        tc_dialect: "英語，粵語及普通話",
        sc_dialect: "英語，粵語及普通話",
        en_clinic: "門診：銅鑼灣診所",
        tc_clinic: "門診：銅鑼灣診所",
        sc_clinic: "門診：銅鑼灣診所",
        visible: true,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        picture: "/images/Member01S0101.png",
        alttext: "樊志偉醫生",
        slug: "樊志偉醫生",
        en_metaname: "泌尿外科專科醫生",
        tc_metaname: "泌尿外科專科醫生",
        sc_metaname: "泌尿外科專科醫生",
        en_metadesc: "周醫生是家庭醫學專科醫生，他在慢性疾病管理（例如高血壓，糖尿病和心理健康）方面經驗豐富。",
        tc_metadesc: "周醫生是家庭醫學專科醫生，他在慢性疾病管理（例如高血壓，糖尿病和心理健康）方面經驗豐富。",
        sc_metadesc: "周醫生是家庭醫學專科醫生，他在慢性疾病管理（例如高血壓，糖尿病和心理健康）方面經驗豐富。",
        en_name: "Dr. Fan Zhiwei",
        tc_name: "樊志偉醫生",
        sc_name: "樊志伟医生",
        en_title: "泌尿外科專科醫生",
        tc_title: "泌尿外科專科醫生",
        sc_title: "泌尿外科專科醫生",
        en_description: "周醫生是家庭醫學專科醫生，他在慢性疾病管理（例如高血壓，糖尿病和心理健康）方面經驗豐富。",
        tc_description: "周醫生是家庭醫學專科醫生，他在慢性疾病管理（例如高血壓，糖尿病和心理健康）方面經驗豐富。",
        sc_description: "周醫生是家庭醫學專科醫生，他在慢性疾病管理（例如高血壓，糖尿病和心理健康）方面經驗豐富。",
        en_dialect: "英語，粵語及普通話",
        tc_dialect: "英語，粵語及普通話",
        sc_dialect: "英語，粵語及普通話",
        en_clinic: "門診：銅鑼灣診所",
        tc_clinic: "門診：銅鑼灣診所",
        sc_clinic: "門診：銅鑼灣診所",
        visible: true,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        picture: "/images/Member01S0101.png",
        alttext: "樊志偉醫生",
        slug: "樊志偉醫生",
        en_metaname: "泌尿外科專科醫生",
        tc_metaname: "泌尿外科專科醫生",
        sc_metaname: "泌尿外科專科醫生",
        en_metadesc: "周醫生是家庭醫學專科醫生，他在慢性疾病管理（例如高血壓，糖尿病和心理健康）方面經驗豐富。",
        tc_metadesc: "周醫生是家庭醫學專科醫生，他在慢性疾病管理（例如高血壓，糖尿病和心理健康）方面經驗豐富。",
        sc_metadesc: "周醫生是家庭醫學專科醫生，他在慢性疾病管理（例如高血壓，糖尿病和心理健康）方面經驗豐富。",
        en_name: "Dr. Fan Zhiwei",
        tc_name: "樊志偉醫生",
        sc_name: "樊志伟医生",
        en_title: "泌尿外科專科醫生",
        tc_title: "泌尿外科專科醫生",
        sc_title: "泌尿外科專科醫生",
        en_description: "周醫生是家庭醫學專科醫生，他在慢性疾病管理（例如高血壓，糖尿病和心理健康）方面經驗豐富。",
        tc_description: "周醫生是家庭醫學專科醫生，他在慢性疾病管理（例如高血壓，糖尿病和心理健康）方面經驗豐富。",
        sc_description: "周醫生是家庭醫學專科醫生，他在慢性疾病管理（例如高血壓，糖尿病和心理健康）方面經驗豐富。",
        en_dialect: "英語，粵語及普通話",
        tc_dialect: "英語，粵語及普通話",
        sc_dialect: "英語，粵語及普通話",
        en_clinic: "門診：銅鑼灣診所",
        tc_clinic: "門診：銅鑼灣診所",
        sc_clinic: "門診：銅鑼灣診所",
        visible: true,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        picture: "/images/Member01S0101.png",
        alttext: "樊志偉醫生",
        slug: "樊志偉醫生",
        en_metaname: "泌尿外科專科醫生",
        tc_metaname: "泌尿外科專科醫生",
        sc_metaname: "泌尿外科專科醫生",
        en_metadesc: "周醫生是家庭醫學專科醫生，他在慢性疾病管理（例如高血壓，糖尿病和心理健康）方面經驗豐富。",
        tc_metadesc: "周醫生是家庭醫學專科醫生，他在慢性疾病管理（例如高血壓，糖尿病和心理健康）方面經驗豐富。",
        sc_metadesc: "周醫生是家庭醫學專科醫生，他在慢性疾病管理（例如高血壓，糖尿病和心理健康）方面經驗豐富。",
        en_name: "Dr. Fan Zhiwei",
        tc_name: "樊志偉醫生",
        sc_name: "樊志伟医生",
        en_title: "泌尿外科專科醫生",
        tc_title: "泌尿外科專科醫生",
        sc_title: "泌尿外科專科醫生",
        en_description: "周醫生是家庭醫學專科醫生，他在慢性疾病管理（例如高血壓，糖尿病和心理健康）方面經驗豐富。",
        tc_description: "周醫生是家庭醫學專科醫生，他在慢性疾病管理（例如高血壓，糖尿病和心理健康）方面經驗豐富。",
        sc_description: "周醫生是家庭醫學專科醫生，他在慢性疾病管理（例如高血壓，糖尿病和心理健康）方面經驗豐富。",
        en_dialect: "英語，粵語及普通話",
        tc_dialect: "英語，粵語及普通話",
        sc_dialect: "英語，粵語及普通話",
        en_clinic: "門診：銅鑼灣診所",
        tc_clinic: "門診：銅鑼灣診所",
        sc_clinic: "門診：銅鑼灣診所",
        visible: true,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        picture: "/images/Member01S0101.png",
        alttext: "樊志偉醫生",
        slug: "樊志偉醫生",
        en_metaname: "泌尿外科專科醫生",
        tc_metaname: "泌尿外科專科醫生",
        sc_metaname: "泌尿外科專科醫生",
        en_metadesc: "周醫生是家庭醫學專科醫生，他在慢性疾病管理（例如高血壓，糖尿病和心理健康）方面經驗豐富。",
        tc_metadesc: "周醫生是家庭醫學專科醫生，他在慢性疾病管理（例如高血壓，糖尿病和心理健康）方面經驗豐富。",
        sc_metadesc: "周醫生是家庭醫學專科醫生，他在慢性疾病管理（例如高血壓，糖尿病和心理健康）方面經驗豐富。",
        en_name: "Dr. Fan Zhiwei",
        tc_name: "樊志偉醫生",
        sc_name: "樊志伟医生",
        en_title: "泌尿外科專科醫生",
        tc_title: "泌尿外科專科醫生",
        sc_title: "泌尿外科專科醫生",
        en_description: "周醫生是家庭醫學專科醫生，他在慢性疾病管理（例如高血壓，糖尿病和心理健康）方面經驗豐富。",
        tc_description: "周醫生是家庭醫學專科醫生，他在慢性疾病管理（例如高血壓，糖尿病和心理健康）方面經驗豐富。",
        sc_description: "周醫生是家庭醫學專科醫生，他在慢性疾病管理（例如高血壓，糖尿病和心理健康）方面經驗豐富。",
        en_dialect: "英語，粵語及普通話",
        tc_dialect: "英語，粵語及普通話",
        sc_dialect: "英語，粵語及普通話",
        en_clinic: "門診：銅鑼灣診所",
        tc_clinic: "門診：銅鑼灣診所",
        sc_clinic: "門診：銅鑼灣診所",
        visible: true,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        picture: "/images/Member01S0101.png",
        alttext: "樊志偉醫生",
        slug: "樊志偉醫生",
        en_metaname: "泌尿外科專科醫生",
        tc_metaname: "泌尿外科專科醫生",
        sc_metaname: "泌尿外科專科醫生",
        en_metadesc: "周醫生是家庭醫學專科醫生，他在慢性疾病管理（例如高血壓，糖尿病和心理健康）方面經驗豐富。",
        tc_metadesc: "周醫生是家庭醫學專科醫生，他在慢性疾病管理（例如高血壓，糖尿病和心理健康）方面經驗豐富。",
        sc_metadesc: "周醫生是家庭醫學專科醫生，他在慢性疾病管理（例如高血壓，糖尿病和心理健康）方面經驗豐富。",
        en_name: "Dr. Fan Zhiwei",
        tc_name: "樊志偉醫生",
        sc_name: "樊志伟医生",
        en_title: "泌尿外科專科醫生",
        tc_title: "泌尿外科專科醫生",
        sc_title: "泌尿外科專科醫生",
        en_description: "周醫生是家庭醫學專科醫生，他在慢性疾病管理（例如高血壓，糖尿病和心理健康）方面經驗豐富。",
        tc_description: "周醫生是家庭醫學專科醫生，他在慢性疾病管理（例如高血壓，糖尿病和心理健康）方面經驗豐富。",
        sc_description: "周醫生是家庭醫學專科醫生，他在慢性疾病管理（例如高血壓，糖尿病和心理健康）方面經驗豐富。",
        en_dialect: "英語，粵語及普通話",
        tc_dialect: "英語，粵語及普通話",
        sc_dialect: "英語，粵語及普通話",
        en_clinic: "門診：銅鑼灣診所",
        tc_clinic: "門診：銅鑼灣診所",
        sc_clinic: "門診：銅鑼灣診所",
        visible: true,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        picture: "/images/Member01S0101.png",
        alttext: "樊志偉醫生",
        slug: "樊志偉醫生",
        en_metaname: "泌尿外科專科醫生",
        tc_metaname: "泌尿外科專科醫生",
        sc_metaname: "泌尿外科專科醫生",
        en_metadesc: "周醫生是家庭醫學專科醫生，他在慢性疾病管理（例如高血壓，糖尿病和心理健康）方面經驗豐富。",
        tc_metadesc: "周醫生是家庭醫學專科醫生，他在慢性疾病管理（例如高血壓，糖尿病和心理健康）方面經驗豐富。",
        sc_metadesc: "周醫生是家庭醫學專科醫生，他在慢性疾病管理（例如高血壓，糖尿病和心理健康）方面經驗豐富。",
        en_name: "Dr. Fan Zhiwei",
        tc_name: "樊志偉醫生",
        sc_name: "樊志伟医生",
        en_title: "泌尿外科專科醫生",
        tc_title: "泌尿外科專科醫生",
        sc_title: "泌尿外科專科醫生",
        en_description: "周醫生是家庭醫學專科醫生，他在慢性疾病管理（例如高血壓，糖尿病和心理健康）方面經驗豐富。",
        tc_description: "周醫生是家庭醫學專科醫生，他在慢性疾病管理（例如高血壓，糖尿病和心理健康）方面經驗豐富。",
        sc_description: "周醫生是家庭醫學專科醫生，他在慢性疾病管理（例如高血壓，糖尿病和心理健康）方面經驗豐富。",
        en_dialect: "英語，粵語及普通話",
        tc_dialect: "英語，粵語及普通話",
        sc_dialect: "英語，粵語及普通話",
        en_clinic: "門診：銅鑼灣診所",
        tc_clinic: "門診：銅鑼灣診所",
        sc_clinic: "門診：銅鑼灣診所",
        visible: true,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        picture: "/images/Member01S0101.png",
        alttext: "樊志偉醫生",
        slug: "樊志伟医生",
        en_metaname: "泌尿外科專科醫生",
        tc_metaname: "泌尿外科專科醫生",
        sc_metaname: "泌尿外科專科醫生",
        en_metadesc: "周醫生是家庭醫學專科醫生，他在慢性疾病管理（例如高血壓，糖尿病和心理健康）方面經驗豐富。",
        tc_metadesc: "周醫生是家庭醫學專科醫生，他在慢性疾病管理（例如高血壓，糖尿病和心理健康）方面經驗豐富。",
        sc_metadesc: "周醫生是家庭醫學專科醫生，他在慢性疾病管理（例如高血壓，糖尿病和心理健康）方面經驗豐富。",
        en_name: "Dr. Fan Zhiwei",
        tc_name: "樊志偉醫生",
        sc_name: "樊志伟医生",
        en_title: "泌尿外科專科醫生",
        tc_title: "泌尿外科專科醫生",
        sc_title: "泌尿外科專科醫生",
        en_description: "周醫生是家庭醫學專科醫生，他在慢性疾病管理（例如高血壓，糖尿病和心理健康）方面經驗豐富。",
        tc_description: "周醫生是家庭醫學專科醫生，他在慢性疾病管理（例如高血壓，糖尿病和心理健康）方面經驗豐富。",
        sc_description: "周醫生是家庭醫學專科醫生，他在慢性疾病管理（例如高血壓，糖尿病和心理健康）方面經驗豐富。",
        en_dialect: "英語，粵語及普通話",
        tc_dialect: "英語，粵語及普通話",
        sc_dialect: "英語，粵語及普通話",
        en_clinic: "門診：銅鑼灣診所",
        tc_clinic: "門診：銅鑼灣診所",
        sc_clinic: "門診：銅鑼灣診所",
        visible: true,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        picture: "/images/Member01S0101.png",
        alttext: "樊志偉醫生",
        slug: "樊志伟医生",
        en_metaname: "泌尿外科專科醫生",
        tc_metaname: "泌尿外科專科醫生",
        sc_metaname: "泌尿外科專科醫生",
        en_metadesc: "周醫生是家庭醫學專科醫生，他在慢性疾病管理（例如高血壓，糖尿病和心理健康）方面經驗豐富。",
        tc_metadesc: "周醫生是家庭醫學專科醫生，他在慢性疾病管理（例如高血壓，糖尿病和心理健康）方面經驗豐富。",
        sc_metadesc: "周醫生是家庭醫學專科醫生，他在慢性疾病管理（例如高血壓，糖尿病和心理健康）方面經驗豐富。",
        en_name: "Dr. Fan Zhiwei",
        tc_name: "樊志偉醫生",
        sc_name: "樊志伟医生",
        en_title: "泌尿外科專科醫生",
        tc_title: "泌尿外科專科醫生",
        sc_title: "泌尿外科專科醫生",
        en_description: "周醫生是家庭醫學專科醫生，他在慢性疾病管理（例如高血壓，糖尿病和心理健康）方面經驗豐富。",
        tc_description: "周醫生是家庭醫學專科醫生，他在慢性疾病管理（例如高血壓，糖尿病和心理健康）方面經驗豐富。",
        sc_description: "周醫生是家庭醫學專科醫生，他在慢性疾病管理（例如高血壓，糖尿病和心理健康）方面經驗豐富。",
        en_dialect: "英語，粵語及普通話",
        tc_dialect: "英語，粵語及普通話",
        sc_dialect: "英語，粵語及普通話",
        en_clinic: "門診：銅鑼灣診所",
        tc_clinic: "門診：銅鑼灣診所",
        sc_clinic: "門診：銅鑼灣診所",
        visible: true,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        picture: "/images/Member01S0101.png",
        alttext: "樊志偉醫生",
        slug: "樊志伟医生",
        en_metaname: "泌尿外科專科醫生",
        tc_metaname: "泌尿外科專科醫生",
        sc_metaname: "泌尿外科專科醫生",
        en_metadesc: "周醫生是家庭醫學專科醫生，他在慢性疾病管理（例如高血壓，糖尿病和心理健康）方面經驗豐富。",
        tc_metadesc: "周醫生是家庭醫學專科醫生，他在慢性疾病管理（例如高血壓，糖尿病和心理健康）方面經驗豐富。",
        sc_metadesc: "周醫生是家庭醫學專科醫生，他在慢性疾病管理（例如高血壓，糖尿病和心理健康）方面經驗豐富。",
        en_name: "Dr. Fan Zhiwei",
        tc_name: "樊志偉醫生",
        sc_name: "樊志伟医生",
        en_title: "泌尿外科專科醫生",
        tc_title: "泌尿外科專科醫生",
        sc_title: "泌尿外科專科醫生",
        en_description: "周醫生是家庭醫學專科醫生，他在慢性疾病管理（例如高血壓，糖尿病和心理健康）方面經驗豐富。",
        tc_description: "周醫生是家庭醫學專科醫生，他在慢性疾病管理（例如高血壓，糖尿病和心理健康）方面經驗豐富。",
        sc_description: "周醫生是家庭醫學專科醫生，他在慢性疾病管理（例如高血壓，糖尿病和心理健康）方面經驗豐富。",
        en_dialect: "英語，粵語及普通話",
        tc_dialect: "英語，粵語及普通話",
        sc_dialect: "英語，粵語及普通話",
        en_clinic: "門診：銅鑼灣診所",
        tc_clinic: "門診：銅鑼灣診所",
        sc_clinic: "門診：銅鑼灣診所",
        visible: true,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        picture: "/images/Member01S0101.png",
        alttext: "樊志偉醫生",
        slug: "樊志伟医生",
        en_metaname: "泌尿外科專科醫生",
        tc_metaname: "泌尿外科專科醫生",
        sc_metaname: "泌尿外科專科醫生",
        en_metadesc: "周醫生是家庭醫學專科醫生，他在慢性疾病管理（例如高血壓，糖尿病和心理健康）方面經驗豐富。",
        tc_metadesc: "周醫生是家庭醫學專科醫生，他在慢性疾病管理（例如高血壓，糖尿病和心理健康）方面經驗豐富。",
        sc_metadesc: "周醫生是家庭醫學專科醫生，他在慢性疾病管理（例如高血壓，糖尿病和心理健康）方面經驗豐富。",
        en_name: "Dr. Fan Zhiwei",
        tc_name: "樊志偉醫生",
        sc_name: "樊志伟医生",
        en_title: "泌尿外科專科醫生",
        tc_title: "泌尿外科專科醫生",
        sc_title: "泌尿外科專科醫生",
        en_description: "周醫生是家庭醫學專科醫生，他在慢性疾病管理（例如高血壓，糖尿病和心理健康）方面經驗豐富。",
        tc_description: "周醫生是家庭醫學專科醫生，他在慢性疾病管理（例如高血壓，糖尿病和心理健康）方面經驗豐富。",
        sc_description: "周醫生是家庭醫學專科醫生，他在慢性疾病管理（例如高血壓，糖尿病和心理健康）方面經驗豐富。",
        en_dialect: "英語，粵語及普通話",
        tc_dialect: "英語，粵語及普通話",
        sc_dialect: "英語，粵語及普通話",
        en_clinic: "門診：銅鑼灣診所",
        tc_clinic: "門診：銅鑼灣診所",
        sc_clinic: "門診：銅鑼灣診所",
        visible: true,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        picture: "/images/Member01S0101.png",
        alttext: "樊志偉醫生",
        slug: "樊志偉醫生",
        en_metaname: "泌尿外科專科醫生",
        tc_metaname: "泌尿外科專科醫生",
        sc_metaname: "泌尿外科專科醫生",
        en_metadesc: "周醫生是家庭醫學專科醫生，他在慢性疾病管理（例如高血壓，糖尿病和心理健康）方面經驗豐富。",
        tc_metadesc: "周醫生是家庭醫學專科醫生，他在慢性疾病管理（例如高血壓，糖尿病和心理健康）方面經驗豐富。",
        sc_metadesc: "周醫生是家庭醫學專科醫生，他在慢性疾病管理（例如高血壓，糖尿病和心理健康）方面經驗豐富。",
        en_name: "Dr. Fan Zhiwei",
        tc_name: "樊志偉醫生",
        sc_name: "樊志伟医生",
        en_title: "泌尿外科專科醫生",
        tc_title: "泌尿外科專科醫生",
        sc_title: "泌尿外科專科醫生",
        en_description: "周醫生是家庭醫學專科醫生，他在慢性疾病管理（例如高血壓，糖尿病和心理健康）方面經驗豐富。",
        tc_description: "周醫生是家庭醫學專科醫生，他在慢性疾病管理（例如高血壓，糖尿病和心理健康）方面經驗豐富。",
        sc_description: "周醫生是家庭醫學專科醫生，他在慢性疾病管理（例如高血壓，糖尿病和心理健康）方面經驗豐富。",
        en_dialect: "英語，粵語及普通話",
        tc_dialect: "英語，粵語及普通話",
        sc_dialect: "英語，粵語及普通話",
        en_clinic: "門診：銅鑼灣診所",
        tc_clinic: "門診：銅鑼灣診所",
        sc_clinic: "門診：銅鑼灣診所",
        visible: true,
        created_at: new Date(),
        updated_at: new Date()
      }
    ], {});
  },

  down: async (queryInterface, Sequelize) => {
    return queryInterface.bulkDelete('doctors', null, {});
  }
};
